---
AWSTemplateFormatVersion: "2010-09-09"
Description: Virtual Private Cloud (VPC) for my personal production worthy projects

Metadata: {}

Parameters:
  Environment:
    Type: String
    Default: Prod
    AllowedValues:
      - Dev
      - Staging
      - Prod

  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet01CIDR:
    Type: String
    Default: 10.0.0.0/24

  PublicSubnet02CIDR:
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnet01CIDR:
    Type: String
    Default: 10.0.2.0/24

  PrivateSubnet02CIDR:
    Type: String
    Default: 10.0.3.0/24

Resources: {}

Outputs: {}
